ministryofjustice/make-recall-decision-ui

- README.md
- docker-compose.yml
> Add env vars for UI app to docker-compose.yml

- integration_tests/integration/caseSummary.spec.ts
- integration_tests/integration/personSearch.spec.ts
- server/middleware/caseSummary.test.ts
- server/middleware/caseSummary.ts
- server/views/pages/caseSummary.njk
- server/views/pages/personSearchResults.njk
- server/views/partials/caseContactLog.njk
- server/views/partials/caseLicenceConditions.njk
- server/views/partials/caseLicenceHistory.njk
- server/views/partials/caseOverview.njk
- server/views/partials/caseRisk.njk
also, change h1 headings for case summary sections
> MRD-6 - no search results

- integration_tests/index.d.ts
- integration_tests/support/commands.ts
- package.json
Also, for `typecheck` task, no need to output files, will speed it up
> Fix types for integration tests

- package-lock.json
- package.json
- server/data/redisClient.ts
- server/data/tokenStore.test.ts
- server/data/tokenStore.ts
- server/middleware/setUpWebSession.ts
To see if it fixes connection problems
> Downgrade Redis to v3

- .env.sample
- ARN_openapi.json
- README.md
- docs/lint-tests.md
- e2e_tests/cypress.json
- e2e_tests/support/commands.ts
- feature.env
- helm_deploy/make-recall-decision-ui/values.yaml
- scripts/start-services-no-ui.sh
also, point readiness probe to /health endpoint
> Add script to run app locally; update readme

- package-lock.json
- package.json
This should resolve the outdated check errors
> Update typescript to 4.6.4

- api/responses/get-case-risk.json
- assets/sass/local.sass
- cypress_shared/commands.ts
- cypress_shared/index.d.ts
- integration_tests/integration/caseSummary.spec.ts
- server/views/components/oasys-card/macro.njk
- server/views/components/oasys-card/template.njk
- server/views/partials/caseRisk.njk
- server/views/partials/layout.njk
as per [prototype](https://makerecall-prototype.apps.live.cloud-platform.service.justice.gov.uk/case-v3/risk?v=1)
- Details of the risk
- Who is at risk
- Circumstances that will increase the risk
> MRD-115 - Add content panels to risk page

- scripts/start-services-no-ui.sh
ref https://github.com/ministryofjustice/make-recall-decision-api/pull/52
> Run docker compose in API now we have dependencies

- api/responses/contact-summary.json
- api/responses/get-case-licence-history.json
- api/responses/get-case-overview.json
- api/responses/get-case-personal-details.json
- api/responses/get-case-risk.json
- integration_tests/integration/caseSummary.spec.ts
- scripts/start-services-no-ui.sh
- server/@types/make-recall-decision-api/models/CaseContactLog.ts
- server/@types/make-recall-decision-api/models/CaseLicenceConditions.ts
- server/@types/make-recall-decision-api/models/CaseLicenceHistory.ts
- server/@types/make-recall-decision-api/models/CaseOverview.ts
- server/@types/make-recall-decision-api/models/CasePersonalDetails.ts
- server/@types/make-recall-decision-api/models/CaseRisk.ts
- server/config.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/utils/index.ts
- server/views/pages/caseSummary.njk
- server/views/partials/caseOverview.njk
- rename personDetails to personalDetailsOverview
- offences list - show all
- start script change - HMPPS auth run via API's docker compose
- timeout for calls to MRD API increased
> MRD-35 - offences

- api/responses/get-case-licence-history.json
- integration_tests/integration/caseSummary.spec.ts
- scripts/start-services-no-ui.sh
- server/utils/dates/index.test.ts
- server/utils/dates/index.ts
- server/views/components/oasys-card/template.njk
- server/views/pages/caseSummary.njk
- server/views/partials/caseLicenceHistory.njk
- use card layout
- use full month names for date format
- startup script - externalise env vars
> MRD-143 - Show cards for licence history contacts

- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/utils/index.ts
- server/data/fetchFromCacheOrApi.test.ts
- server/data/fetchFromCacheOrApi.ts
- server/data/redisClient.ts
- server/views/pages/caseSummary.njk
- cache for 1hr
- when reading, if cache is empty then fetch from API
> MRD-153 - Cache licence history API response in Redis

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/app.ts
- server/errorHandler.test.ts
- server/errorHandler.ts
- server/routes/testutils/appSetup.ts
- server/views/pages/error-404.njk
- server/views/pages/error.njk
- separate error page for 404
- server error page shows error stack if not in prod
- fix font
> MRD-155 - 404 and server error pages

- integration_tests/integration/caseSummary.spec.ts
- server/@types/index.d.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/caseSummary.ts
- server/controllers/caseSummary/utils/index.ts
- server/controllers/personSearch/validators/validatePersonSearch.test.ts
- server/controllers/personSearch/validators/validatePersonSearch.ts
- server/data/fetchFromCacheOrApi.test.ts
- server/data/fetchFromCacheOrApi.ts
- server/views/pages/caseSummary.njk
- server/views/partials/caseLicenceHistory.njk
- server/views/partials/caseLicenceHistoryData.njk
- server/views/partials/casePersonalDetails.njk
- Bug fix - convert CRNs from URL to uppercase
- Redis cache - shorten TTL to 10 minutes
- Licence history - split table to separate page
- Person details - if email / phone missing then hide label
> MRD-158 - Convert query CRN to uppercase / misc other

- assets/sass/local.scss
- integration_tests/integration/caseSummary.spec.ts
- server/views/partials/caseLicenceHistoryData.njk
- server/views/partials/casePersonalDetails.njk
Also, on personal details - rename offender manager to probation practitioner
> Licence history data - fixed table layout

- api/responses/get-case-licence-history.json
- integration_tests/integration/caseSummary.spec.ts
- integration_tests/integration/personSearch.spec.ts
- server/utils/dates/format.test.ts
- server/utils/dates/format.ts
- server/utils/dates/index.test.ts
- server/utils/dates/index.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.ts
- server/views/pages/caseSummary.njk
- server/views/pages/personSearchResults.njk
- server/views/partials/caseLicenceHistory.njk
- server/views/partials/caseLicenceHistoryData.njk
- dates from the API are now including a UTC marker Z
- update the date formatter to adjust to daylight saving time for timezone europe/london
> MRD-161 - Update date formatter to use timezone

- api/responses/get-case-overview.json
- api/responses/get-case-personal-details.json
- integration_tests/integration/caseSummary.spec.ts
- server/views/partials/caseOverview.njk
- server/views/partials/casePersonalDetails.njk
> MRD-167 - Move risk flags from personal details to overview page

- assets/sass/local.scss
- integration_tests/integration/licenceHistory.spec.ts
- server/middleware/featureFlags.ts
- server/utils/errors.test.ts
- server/utils/errors.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/caseSummary.njk
- server/views/partials/caseLicenceHistory.njk
- server/views/partials/layout.njk
- Prefix page title with "Error:" if page has errors
- Add 'show / hide filter' toggle button for mobile
- enable feature flag by default
- move error summary up page, above main heading
Also, on cards:
- hide notes section if there are none
> MRD-148 - date filter changes

- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/licenceHistory.spec.ts
- server/controllers/caseSummary/utils/filterContactsByDateRange.test.ts
- server/controllers/caseSummary/utils/filterContactsByDateRange.ts
- server/controllers/caseSummary/utils/transformLicenceHistory.test.ts
- server/utils/dates/convert.test.ts
- server/utils/dates/convert.ts
- server/utils/dates/format.test.ts
- server/utils/dates/format.ts
also, if user enters current year as 2 digits, assume it's current century
> MRD-148 - Format date filter tag with month name not number

- api/responses/get-case-licence-history.json
- api/responses/get-contact-types.json
- cypress_shared/commands.ts
- cypress_shared/index.d.ts
- integration_tests/integration/licenceHistory.spec.ts
- server/@types/index.d.ts
- server/@types/make-recall-decision-api/models/ContactSummaryResponse.ts
- server/@types/make-recall-decision-api/models/ContactTypeGroup.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/utils/filterContactsByContactType.test.ts
- server/controllers/caseSummary/utils/filterContactsByContactType.ts
- server/controllers/caseSummary/utils/filterContactsByDateRange.test.ts
- server/controllers/caseSummary/utils/filterContactsByDateRange.ts
- server/controllers/caseSummary/utils/transformLicenceHistory.test.ts
- server/controllers/caseSummary/utils/transformLicenceHistory.ts
- server/utils/errors.ts
- server/utils/nunjucks.test.ts
- server/utils/nunjucks.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/partials/caseLicenceHistory.njk
- server/views/partials/contactFilters.njk
- server/views/partials/layout.njk
- under feature flag 'contactTypesFilter' (off by default)
- next to each contact type checkbox, put the number of results for that type
> MRD-148 - Filter by contact type (mock contact types data)

- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/caseSummary.spec.ts
- integration_tests/integration/licenceConditions.spec.ts
- server/controllers/caseSummary/utils/getCaseSection.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.test.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.ts
- server/views/partials/caseLicenceConditions.njk
- show main offence only
- show 'Not available' for any empty field, or in place of licence conditions table if there are no conditions
- for licence conditions page, suffix with person name, for screen readers
> MRD-191 - Licence conditions - main offence only; message if no conditions

- README.md
- api/responses/get-case-licence-conditions.json
- integration_tests/integration/analytics.spec.ts
- integration_tests/integration/licenceConditions.spec.ts
- server/@types/make-recall-decision-api/models/LicenceConditionsResponse.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.test.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.ts
- server/middleware/setUpWebSecurity.ts
- server/views/partials/caseLicenceConditions.njk
also, update content security policy to allow GA script to load
> MRD-184 - Renamed key from licence conditions API response (offences -> convictions)

- README.md
- integration_tests/integration/analytics.spec.ts
- integration_tests/integration/contactHistory.spec.ts
- integration_tests/support/commands.ts
- package.json
- server/@types/dates.d.ts
- server/controllers/caseSummary/utils/filterContactsBySearch.test.ts
- server/controllers/caseSummary/utils/filterContactsSearch.ts
- server/controllers/caseSummary/utils/transformContactHistory.test.ts
- server/controllers/caseSummary/utils/transformContactHistory.ts
- server/middleware/featureFlags.ts
- server/utils/errors.test.ts
- server/utils/errors.ts
- server/views/partials/contactFilters.njk
> MRD-205 - Contacts free text search

- .circleci/config.yml
- e2e_tests/integration/caseSummary.feature
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/caseSummary.spec.ts
- server/middleware/featureFlags.ts
- server/views/pages/caseSummary.njk
Also
- skip CI preprod E2E test (temporary measure while preprod env unavailable)
- add 'wait' check to make integration tests more robust
> MRD-215 - Hide risk page under feature flag

- api/responses/get-case-licence-conditions.json
- integration_tests/integration/licenceConditions.spec.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.test.ts
- server/controllers/caseSummary/utils/transformLicenceConditions.ts
- server/views/partials/caseContactHistory.njk
- server/views/partials/caseLicenceConditions.njk
also, MRD-220 - Visually hide h1 on contact history page
> MRD-184 - show additional licence conditions

- integration_tests/integration/contactHistory.spec.ts
- server/controllers/caseSummary/utils/filterContactsBySearch.test.ts
- server/controllers/caseSummary/utils/filterContactsBySearch.ts
- server/controllers/caseSummary/utils/transformContactHistory.test.ts
- server/controllers/caseSummary/utils/transformContactHistory.ts
- server/views/partials/contactFilters.njk
> MRD-205 - Allow multiple search terms

- integration_tests/integration/contactHistory.spec.ts
- server/controllers/caseSummary/utils/filterContactsBySearch.test.ts
- server/controllers/caseSummary/utils/transformContactHistory.test.ts
- server/utils/errors.test.ts
- server/utils/errors.ts
- server/views/partials/contactFilters.njk
Change heading to 'Search term'
Update validation error message
> MRD-205 - Copy changes

- cypress_shared/commands.ts
- cypress_shared/index.d.ts
- integration_tests/integration/featureFlags.spec.ts
- server/@types/index.d.ts
- server/controllers/featureFlags/index.ts
- server/middleware/featureFlags.test.ts
- server/middleware/featureFlags.ts
- server/routes/index.ts
- server/routes/routeUrls.ts
- server/views/pages/featureFlags.njk
> MRD-207 - Feature flags page

- server/@types/make-recall-decision-api/models/CaseSummaryOverviewResponse.ts
- server/@types/make-recall-decision-api/models/ContactGroupResponse.ts
- server/@types/make-recall-decision-api/models/ContactHistoryResponse.ts
- server/@types/make-recall-decision-api/models/ContactTypeGroup.ts
- server/@types/make-recall-decision-api/models/ConvictionResponse.ts
- server/@types/make-recall-decision-api/models/LicenceConditionsResponse.ts
- server/@types/make-recall-decision-api/models/PersonDetailsResponse.ts
- server/controllers/caseSummary/caseSummary.ts
- server/controllers/caseSummary/contactHistory/filterContactsByContactType.ts
- server/controllers/caseSummary/contactHistory/helpers/contactTypes.ts
- server/controllers/caseSummary/contactHistory/helpers/decorateGroups.ts
- server/controllers/caseSummary/getCaseSection.test.ts
- server/controllers/caseSummary/getCaseSection.ts
- server/data/fetchFromCacheOrApi.test.ts
- server/data/fetchFromCacheOrApi.ts
- don't cache the response if it's redacted due to restriction or exclusion
See ticket for all test cases - https://dsdmoj.atlassian.net/browse/MRD-254
> MRD-254 - Control access to cached data via user ID

- integration_tests/integration/risk.spec.ts
- server/controllers/caseSummary/contactHistory/transformContactHistory.test.ts
- server/controllers/caseSummary/contactHistory/transformContactHistory.ts
- server/views/components/oasys-card/template.njk
- server/views/partials/caseRisk.njk
also, pass filtered system contacts on to next filter
> MRD-286 - Show risk predictor scores

- .circleci/config.yml
- audit-ci.json
- package-lock.json
- package.json
Copied from typescript template - https://github.com/ministryofjustice/hmpps-template-typescript/pull/103/files
> Fix security false positive (audit-ci for nodemon)

- server/controllers/recommendation/recommendationForm.ts
- server/views/components/summary-card/_index.scss
- server/views/pages/recommendation/alternatives.njk
- server/views/pages/recommendation/custody.njk
- server/views/pages/recommendation/personalDetails.njk
- server/views/pages/recommendation/selectLicenceConditions.njk
- server/views/pages/recommendation/summary.njk
- server/views/partials/evidenceLicenceConditionsList.njk
> MRD-290 - various fixes

- assets/js/evidence-panel.js
- server/controllers/recommendation/itemSelectedHandler.ts
- server/controllers/recommendation/recommendationForm.ts
- server/controllers/recommendation/selectLicenceConditionsPage.ts
- server/views/components/select-component/template.njk
- server/views/pages/recommendation/selectLicenceConditions.njk
- server/views/pages/recommendation/summary.njk
- server/views/partials/caseContactHistory.njk
- server/views/partials/evidenceContactsList.njk
- server/views/partials/evidenceLicenceConditionsList.njk
also:
- don't store whole JSON for contact / condition in hidden input
- some copy fixes
> MRD-290 - Set default alternatives if no stored recommendation

- .eslintrc.json
- server/AppError.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/caseSummary.ts
- server/controllers/downloadDocument/index.test.ts
- server/controllers/downloadDocument/index.ts
- server/controllers/personSearch/validators/validatePersonSearch.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- shared validation / normalization of CRN
> MRD-328 - Refactor CRN validation

- api/routes.ts
- integration_tests/integration/recommendation.spec.ts
- integration_tests/mockApis/makeRecallDecisionApi.ts
- integration_tests/plugins/index.ts
- server/@types/make-recall-decision-api/models/CreateRecommendationResponse.ts
- server/controllers/caseSummary/getCaseSection.ts
- server/controllers/recommendations/createRecommendation.test.ts
- server/controllers/recommendations/createRecommendation.ts
- server/data/makeDecisionApiClient.ts
- server/middleware/featureFlags.ts
- server/routes/index.ts
- server/views/pages/caseSummary.njk
- server/views/partials/caseContactHistory.njk
- server/views/partials/contactFilters.njk
- 'Make a recommendation' button on case summary pages, under a feature flag
- send a POST to MRD API ([see ticket for contract](https://dsdmoj.atlassian.net/browse/MRD-328))
- on success or failure, redirect to case summary overview (temporary, until next page is built)
- on API error, show error summary at top of page
> MRD-328 - Create a recommendation

- .circleci/config.yml
- api/responses/get-case-overview.json
- assets/sass/_flex.scss
- assets/sass/local.scss
- cypress_shared/commands.ts
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/overview.spec.ts
- server/@types/make-recall-decision-api/models/CaseSummaryOverviewResponse.ts
- server/@types/make-recall-decision-api/models/ConvictionResponse.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/overview/transformOverview.test.ts
- server/controllers/caseSummary/overview/transformOverview.ts
- server/utils/dates/index.test.ts
- server/utils/dates/index.ts
- server/views/partials/caseOverview.njk
- licence box 
- offence & sentence box
- restore dev E2E job
> MRD-375 - Licence and offence / sentence boxes

- assets/sass/application.sass
- assets/sass/components/_notification-banner.scss
- integration_tests/integration/overview.spec.ts
- server/views/partials/caseOverview.njk
- server/views/partials/layout.njk
> MRD-139 - Banner for multiple custodial active convictions

- integration_tests/integration/licenceConditions.spec.ts
- server/views/partials/caseLicenceConditions.njk
to `There are no additional licence conditions in NDelius. Check the licence document.`
> MRD-406 - Update delius message

- e2e_tests/integration/caseSummary.feature
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation.spec.ts
- server/controllers/recommendations/formOptions/recallType.ts
- server/controllers/recommendations/helpers/getDisplayValueForOption.test.ts
- server/controllers/recommendations/helpers/getDisplayValueForOption.ts
- server/controllers/recommendations/helpers/getFormValues.test.ts
- server/controllers/recommendations/helpers/pageMetaData.ts
- server/controllers/recommendations/validators/validateCustodyStatus.test.ts
- server/controllers/recommendations/validators/validateCustodyStatus.ts
- server/controllers/recommendations/validators/validateRecallType.test.ts
- server/textStrings/en.ts
- server/utils/lists.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/recommendations/confirmationPartA.njk
Download part A link is not active yet
> MRD-417 - Part A created confirmation page

- .circleci/config.yml
This reverts commit 75b45addfa15f90f0d3468d9bd40f00679e5fffe.
> Restore e2e dev tests to pipeline

- assets/js/analytics.js
- integration_tests/integration/analytics.spec.ts
- server/views/components/oasys-card/template.njk
- server/views/partials/caseContactHistory.njk
- server/views/partials/caseRisk.njk
- server/views/partials/error-summary.njk
https://docs.google.com/document/d/1BV96AQWLIHGuJvmqeS1i_dUoeYa9xC9dNX-miTOXA7I/edit#
> MRD-539 - Update GA events

- server/views/pages/rec-prototype/noRecallSummary.njk
- server/views/partials/caseRecommendationsPrototype.njk
- recommendations list - show dates only
- task list - change link text for 'recall type'
> MRD-500 - UR prototype tweaks

- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation.spec.ts
- integration_tests/integration/risk.spec.ts
- server/controllers/recommendations/vulnerabilities/formValidator.test.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/localPoliceContactDetails.njk
also, remove 'optional' label for phone and email
> MRD-498 - Vulnerability error message

- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation.spec.ts
- integration_tests/support/commands.ts
- server/@types/make-recall-decision-api/index.d.ts
- server/@types/make-recall-decision-api/models/Mappa.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/controllers/recommendations/getRecommendationPage.ts
- server/controllers/recommendations/helpers/taskCompleteness.test.ts
- server/controllers/recommendations/helpers/taskCompleteness.ts
- server/views/pages/caseSummary.njk
- server/views/pages/recommendations/taskList.njk
also, use a utility to work out completeness status
> MRD-551 - Task list - link from Update rec button

- api/responses/get-recommendation.json
- e2e_tests/integration/caseSummary.feature
- e2e_tests/integration/stepDefinitions/index.ts
- e2e_tests/support/commands.ts
- integration_tests/integration/recommendation-task-list.spec.ts
- integration_tests/integration/recommendation.spec.ts
- server/@types/index.d.ts
- server/@types/make-recall-decision-api/models/IndeterminateSentenceType.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/controllers/recommendations/helpers/formOptions.ts
- server/controllers/recommendations/helpers/pageMetaData.ts
- server/controllers/recommendations/helpers/taskCompleteness.test.ts
- server/controllers/recommendations/helpers/taskCompleteness.ts
- server/controllers/recommendations/indeterminateSentenceType/formOptions.ts
- server/controllers/recommendations/indeterminateSentenceType/formValidator.test.ts
- server/controllers/recommendations/indeterminateSentenceType/formValidator.ts
- server/controllers/recommendations/indeterminateSentenceType/inputDisplayValues.test.ts
- server/controllers/recommendations/indeterminateSentenceType/inputDisplayValues.ts
- server/controllers/recommendations/isDeterminateSentence/formValidator.test.ts
- server/controllers/recommendations/isDeterminateSentence/formValidator.ts
- server/controllers/recommendations/isDeterminateSentence/inputDisplayValues.test.ts
- server/controllers/recommendations/isDeterminateSentence/inputDisplayValues.ts
- server/controllers/recommendations/victimContactScheme/formValidator.test.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/indeterminateSentenceType.njk
- server/views/pages/recommendations/taskList.njk
> MRD-606 - Indeterminate sentence type

- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation-task-list.spec.ts
- integration_tests/integration/recommendation.spec.ts
- server/controllers/recommendations/indeterminateSentenceType/formValidator.test.ts
- server/controllers/recommendations/indeterminateSentenceType/formValidator.ts
- server/controllers/recommendations/isExtendedSentence/formValidator.test.ts
- server/controllers/recommendations/isExtendedSentence/formValidator.ts
- server/controllers/recommendations/isExtendedSentence/inputDisplayValues.test.ts
- server/controllers/recommendations/isIndeterminateSentence/formValidator.test.ts
- server/controllers/recommendations/isIndeterminateSentence/formValidator.ts
- server/controllers/recommendations/isIndeterminateSentence/inputDisplayValues.test.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/taskList.njk
also, back links in indeterminate flow return to task list
> MRD-615 - Correct error msg for extended sentence; standardise others

- e2e_tests/integration/caseSummary.feature
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation-task-list.spec.ts
- integration_tests/integration/recommendation.spec.ts
- server/controllers/recommendations/emergencyRecall/formValidator.test.ts
- server/controllers/recommendations/emergencyRecall/formValidator.ts
- server/controllers/recommendations/postRecommendationForm.test.ts
- server/controllers/recommendations/recallType/formValidator.test.ts
- server/controllers/recommendations/recallType/formValidator.ts
- server/controllers/recommendations/recallTypeIndeterminate/formOptions.ts
- server/controllers/recommendations/recallTypeIndeterminate/formValidator.test.ts
- server/controllers/recommendations/recallTypeIndeterminate/formValidator.ts
- server/controllers/recommendations/recallTypeIndeterminate/inputDisplayValues.test.ts
- server/controllers/recommendations/recallTypeIndeterminate/inputDisplayValues.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/emergencyRecall.njk
- server/views/pages/recommendations/recallType.njk
- server/views/pages/recommendations/recallTypeIndeterminate.njk
- server/views/pages/recommendations/sensitiveInformation.njk
- server/views/pages/recommendations/taskList.njk
> MRD-607 - Change standard recall option to emergency recall, for indeterminate sentences

- integration_tests/integration/recommendation.spec.ts
- scripts/autofill-extension-import.csv
- server/controllers/recommendations/isIndeterminateSentence/formValidator.test.ts
- server/controllers/recommendations/isIndeterminateSentence/formValidator.ts
- server/views/pages/recommendations/isIndeterminateSentence.njk
- server/views/pages/recommendations/sensitiveInformation.njk
also, update back link from sensitive info
> MRD-603 - reset subsequent answers if indeterminate answer changed

- api/responses/get-recommendation.json
- integration_tests/integration/no-recall.spec.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/controllers/recommendations/getRecommendationPage.test.ts
- server/controllers/recommendations/getRecommendationPage.ts
- server/controllers/recommendations/helpers/taskCompleteness.test.ts
- server/controllers/recommendations/helpers/taskCompleteness.ts
- server/views/pages/recommendations/taskListNoRecall.njk
- server/views/partials/taskList/circumstances.njk
also - set no caching for recommendation pages
> MRD-629 - Task list for no recall - set statuses

- cypress_shared/commands.ts
- cypress_shared/index.d.ts
- cypress_shared/utils.ts
- e2e_tests/integration/stepDefinitions/caseSummary.ts
- e2e_tests/integration/stepDefinitions/index.ts
- e2e_tests/integration/stepDefinitions/noRecall.ts
- integration_tests/integration/contactHistory.spec.ts
- server/@types/make-recall-decision-api/index.d.ts
- server/@types/make-recall-decision-api/models/ActiveRecommendation.ts
- server/@types/make-recall-decision-api/models/HowWillAppointmentHappen.ts
- server/@types/make-recall-decision-api/models/NextAppointment.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/controllers/recommendations/nextAppointment/inputDisplayValues.test.ts
- server/controllers/recommendations/nextAppointment/inputDisplayValues.ts
- server/controllers/recommendations/reasonsForNoRecall/formValidator.test.ts
- server/controllers/recommendations/reasonsForNoRecall/formValidator.ts
- server/middleware/parseRecommendationUrl.test.ts
- server/middleware/parseRecommendationUrl.ts
- server/views/pages/recommendations/responseToProbation.njk
- E2E util "enterDateTime" accepts object of date parts instead of ISO string
- back links return to no recall task list
- reasons for no recall - validation correction
- response to probation hint - render as HTML
- next appointment - show saved appt type
> MRD-702 - E2E refactor / fixes

- integration_tests/integration/recommendation-task-list.spec.ts
- integration_tests/integration/recommendation.spec.ts
- server/controllers/recommendations/getRecommendationPage.ts
- server/controllers/recommendations/helpers/urls.test.ts
- server/controllers/recommendations/helpers/urls.ts
- server/views/pages/caseSummary.njk
- server/views/pages/recommendations/fixedTermLicenceConditions.njk
- also - fix back button link from fixed term licence conditions page
> MRD-712 - Redirects from task lists

- server/controllers/recommendations/nextAppointment/formValidator.test.ts
- server/controllers/recommendations/nextAppointment/formValidator.ts
- server/controllers/recommendations/reasonsForNoRecall/formValidator.test.ts
- server/controllers/recommendations/reasonsForNoRecall/formValidator.ts
- server/controllers/recommendations/whyConsideredRecall/formValidator.test.ts
- server/controllers/recommendations/whyConsideredRecall/formValidator.ts
- server/views/pages/recommendations/reasonsForNoRecall.njk
- server/views/partials/taskList/createLetter.njk
also - label size + caption on 'reasons for no recall'
> MRD-629 - Create letter tasks - route back to task list, if they were complete

- integration_tests/integration/recommendation.spec.ts
- server/views/pages/recommendations/addressDetails.njk
To address https://dsdmoj.atlassian.net/browse/MRD-631?focusedCommentId=241121
> MRD-631 - Multiple addresses prompt

- server/views/components/predictor-timeline/template.njk
- server/views/partials/caseRisk.njk
To assess data availability. This is still hidden under a feature flag
> MRD-279 - Enable risk predictor score graphs / timeline

- api/responses/get-case-risk.json
- assets/js/predictors.js
- assets/sass/risk/_timeline.scss
- integration_tests/integration/risk.spec.ts
- server/views/components/mappa-widget/template.njk
- server/views/components/predictor-timeline/template.njk
- server/views/partials/caseRisk.njk
also
- last updated date for MAPPA
- hide timeline by default
> MRD-693 - Nest predictor scores under 'scores' key

- integration_tests/integration/overview.spec.ts
- integration_tests/integration/risk.spec.ts
- server/views/components/mappa-widget/template.njk
- server/views/components/oasys-card/template.njk
- server/views/partials/caseRisk.njk
- server/views/partials/overview/contingency-plan.njk
- server/views/partials/overview/offence-description.njk
see commit messages for details
> Risk design tweaks

- api/responses/get-case-risk.json
- assets/sass/risk/_predictor-scores.scss
- integration_tests/integration/risk.spec.ts
- server/controllers/caseSummary/overview/transformRiskManagementPlan.test.ts
- server/views/components/predictor-timeline-item/template.njk
- server/views/partials/caseRisk.njk
see commit messages for individual changes
> Risk tweaks - errors / timeline

- assets/sass/local.scss
- integration_tests/integration/overview.spec.ts
- server/views/components/task-status/template.njk
- server/views/pages/recommendations/confirmationPartA.njk
- server/views/partials/overview/contingency-plan.njk
- server/views/partials/overview/offence-description.njk
- Lower case task list tags only
- font size on confirmation page
- update error messages for index offence / contingency plan
> MRD-752 - misc

- api/responses/get-case-overview.json
- integration_tests/integration/overview.spec.ts
- server/@types/make-recall-decision-api/models/AssessmentInfo.ts
- server/views/pages/recommendations/confirmationNoRecallLetter.njk
- server/views/pages/recommendations/confirmationPartA.njk
- server/views/partials/overview/offence-description.njk
also - font size tweaks on confirmation pages
> MRD-700 - Rename offenceCodesMatch to offencesMatch

- e2e_tests/integration/stepDefinitions/caseSummary.ts
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/accessibility/accessibility.spec.ts
- integration_tests/integration/contactHistory.spec.ts
- integration_tests/integration/featureFlags.spec.ts
- integration_tests/integration/recommendation.spec.ts
- integration_tests/integration/risk.spec.ts
- server/middleware/featureFlags.ts
- server/views/partials/contactFilters.njk
also, remove old flag for contact type filters
> MRD-834 - Enable feature flags for Risk, Make a recommendation, Contact history documents

- integration_tests/integration/excludedRestricted.spec.ts
- server/@types/make-recall-decision-api/models/UserAccessResponse.ts
- server/utils/utils.ts
- server/views/pages/excludedRestrictedCrn.njk
: Attempt to pick up API userNotFound property.
> mrd-856_improve-error-handling-for-delius-user-access-issue

- server.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/getCaseSection.ts
- server/monitoring/azureAppInsights.ts
- server/views/partials/contactFilters.njk
- Show contact type filters if any available
- Send timings for API calls to appInsights
- commented instructions for running with HTTPS
> MRD-802 - a11y tweak; capture API timings

- assets/sass/local.scss
- server/controllers/recommendations/licenceConditions/inputDisplayValues.test.ts
- server/controllers/recommendations/licenceConditions/inputDisplayValues.ts
- server/utils/dates/convert.test.ts
- server/utils/dates/convert.ts
- server/views/pages/caseSummary.njk
- server/views/pages/recommendations/confirmationNoRecallLetter.njk
- server/views/pages/recommendations/confirmationPartA.njk
- server/views/partials/caseContactHistory.njk
- server/views/partials/layout.njk
- Change focus treatment for heading on contact history
- If no tag manager ID, don't write iframe
- Allow undefined date parameters
- attributes for GA click events (make rec / download)
- rec flow - licence conditions - don't error if no additional conditions sent
> MRD-802 - Change focus treatment for heading + small fixes

- e2e_tests/integration/stepDefinitions/caseSummary.ts
Not all the CRNs in dev have them
> MRD-866 - Don't assert on licence properties

- integration_tests/integration/vulnerabilities.spec.ts
- server/views/partials/caseVulnerabilities.njk
- server/views/partials/notificationBanners/vulnerabilitiesError.njk
- server/views/partials/notificationBanners/vulnerabilitiesNone.njk
also, fix font sizes in banners
> MRD-896 - show No for null values

- server/data/healthCheck.ts
> Increase health check timeout to 5s

- assets/js/copyToClipboard.js
- e2e_tests/integration/stepDefinitions/index.ts
- integration_tests/integration/recommendation.spec.ts
- integration_tests/integration/risk.spec.ts
- integration_tests/support/commands.ts
- server/controllers/recommendations/helpers/pageMetaData.ts
- server/data/makeDecisionApiClient.ts
- server/views/components/mappa-widget/template.njk
- server/views/components/rosh-widget/template.njk
- server/views/pages/recommendations/offenceAnalysis.njk
also, update E2E to check for MAPPA data appearing
> MRD-920 - Refresh MAPPA data on the page

- docs/lint-tests.md
- docs/setup-running.md
- e2e_tests/integration/stepDefinitions/index.ts
- e2e_tests/integration/stepDefinitions/recallDeterminate.ts
- e2e_tests/integration/stepDefinitions/recallIndeterminate.ts
- e2e_tests/utils/index.ts
- e2e_tests/utils/test_data/sharedInputData.ts
- server/controllers/recommendations/addPreviousRelease/inputDisplayValues.test.ts
- server/controllers/recommendations/addPreviousRelease/inputDisplayValues.ts
- server/controllers/recommendations/helpers/pageMetaData.ts
- server/controllers/recommendations/helpers/taskCompleteness.test.ts
- server/controllers/recommendations/helpers/taskCompleteness.ts
- server/controllers/recommendations/previousReleases/formValidator.test.ts
- server/controllers/recommendations/previousReleases/formValidator.ts
- server/controllers/recommendations/previousReleases/inputDisplayValues.test.ts
- server/controllers/recommendations/previousReleases/inputDisplayValues.ts
- server/views/pages/recommendations/previousReleases.njk
> MRD-898 - Previous release - validation / value display

- e2e_tests/integration/stepDefinitions/index.ts
As offender details is being checked for the other CRN
> MRD-898 - Swap dev CRNs

- docs/lint-tests.md
- e2e_tests/integration/stepDefinitions/index.ts
- e2e_tests/integration/stepDefinitions/recallIndeterminate.ts
- e2e_tests/utils/test_data/sharedInputData.ts
- scripts/autofill-extension-import.csv
- server/views/components/delius-details-message/macro.njk
- server/views/components/delius-details-message/template.njk
- server/views/pages/recommendations/confirmationPartA.njk
- server/views/pages/recommendations/offenceDetails.njk
- server/views/pages/recommendations/personalDetails.njk
- server/views/pages/recommendations/previousReleases.njk
- server/views/partials/layout.njk
also
- document running E2E against envs
- update autofill CSV
- shared test data for offence analysis
> MRD-797 - update delius message on details pages

- e2e_tests/integration/recallDeterminate.feature
until API PR goes in - https://github.com/ministryofjustice/make-recall-decision-api/pull/513
> Temporarily disable standard E2E check

- helm_deploy/values-preprod.yaml
> Temporarily change auth URL for preprod to avoid ingress

- helm_deploy/values-preprod.yaml
This reverts commit 1ba265e381957cbd8842d45380ba459d91a00ac5.
> Revert "Temporarily change auth URL for preprod to avoid ingress (#480)"

- server/controllers/recommendations/createRecommendation.test.ts
- server/controllers/recommendations/createRecommendation.ts
- server/middleware/featureFlags.ts
to create a domain event when recommendation started
> MRD-892 - Add flagDomainEventRecommendationStarted, pass flags to createRecommendation controller

- assets/sass/_design-system-overrides.scss
- assets/sass/_flex.scss
- assets/sass/application.sass
- assets/sass/local.scss
- integration_tests/integration/recommendationFormValidation.spec.ts
- integration_tests/integration/recommendationRedirects.spec.ts
- server/controllers/recommendations/getRecommendationPage.ts
- server/controllers/recommendations/helpers/urls.test.ts
- server/controllers/recommendations/helpers/urls.ts
- server/views/pages/caseSummary.njk
- server/views/pages/recommendations/managerViewDecision.njk
- Stop 'consider recall' button from wrapping on Edge browser
- redirects for PO / SPO
> MRD-1007 - tweaks

- .circleci/config.yml
This reverts commit 5ecf9cb0d3c50e7f6b1ee87b26d999497a1f95a5.
> Revert "Temporarily remove E2E tests for preprod (#526)"

- assets/js/predictors.js
- assets/sass/_flex.scss
- assets/sass/risk/_predictor-scores.scss
- integration_tests/integration/risk.spec.ts
- server/views/components/predictor-timeline-section/template.njk
- server/views/partials/caseRisk.njk
- reading order
- score graphs  - aria-hidden and visually hidden scores
- timeline - refactor JS, add ARIA attributes
> MRD-1070 - a11y fixes for risk

- .circleci/config.yml
This reverts commit 1c6f3a40a2da8dd4590c16d57b9e774249c6d8bf.
> Restore E2E test on dev

- integration_tests/integration/contactHistory.spec.ts
- server/controllers/caseSummary/caseSummary.test.ts
- server/controllers/caseSummary/caseSummary.ts
- server/controllers/caseSummary/contactHistory/filterContactsBySystemGenerated.ts
- server/controllers/caseSummary/contactHistory/transformContactHistory.test.ts
- server/controllers/caseSummary/contactHistory/transformContactHistory.ts
- server/controllers/caseSummary/getCaseSection.test.ts
- server/controllers/caseSummary/getCaseSection.ts
- server/middleware/featureFlags.ts
- server/views/partials/contactFilters.njk
Do not merge until MRD API removes flag code and always sends sys-gen contacts
> MRD-1004 - Clean up flag code for system generated contacts

- server/views/pages/recommendations/spoRecordDecision.njk
#	server/views/pages/recommendations/spoRecordDecision.njk
> various fixes

- server/routes/routeUrls.ts
As suggested on ticket [in comment here](https://dsdmoj.atlassian.net/browse/MRD-1397?focusedCommentId=291481)
> mrd-1397_feature-flags-disabled-in-prod-and-preprod: flags endpoint disabled for pre-prod and prod

- server/routes/index.ts
- server/routes/routeUrls.ts
- server/utils/utils.ts
> mrd-1397_pre-prod-prod-feature-flags-disabled-env-detection-correction: corrected env variable used for switching on/off feature flags endpoint

- e2e_tests/integration/rationale.feature
- e2e_tests/integration/stepDefinitions/rationaleSPO.ts
- server/controllers/recommendation/spoRecallRationaleController.test.ts
- server/controllers/recommendation/spoRecallRationaleController.ts
- server/routes/recommendations.ts
#	e2e_tests/integration/stepDefinitions/index.ts
> MRD-1450 - fix for AC1

- integration_tests/integration/recommendation.spec.ts
- server/controllers/recommendation/spoRecallRationaleController.test.ts
- server/controllers/recommendation/spoRecallRationaleController.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/spoRecallRationale.njk
#	e2e_tests/integration/stepDefinitions/index.ts
> MRD-1450 - change to heading and copy in first paragraph

- e2e_tests/integration/e2eDNTR.feature
- e2e_tests/integration/stepDefinitions/assertionsDNTR.ts
- e2e_tests/integration/stepDefinitions/rationalePO.ts
- e2e_tests/support/enums.ts
- e2e_tests/utils/index.ts
Write an e2e test for following scenario  - Decision Not To Recall Letter details are correct when PO and SPO records rationale during review and countersign
> MRD-1488 write end to end test for the DNTR journey

- .circleci/config.yml
- e2e_tests/features/e2eLocalTests/contact-information.feature
- e2e_tests/stepDefinitions/index.ts
- e2e_tests/stepDefinitions/rationalePO.ts
- e2e_tests/stepDefinitions/rationaleSPO.ts
MRD-1723 / MRD- 1731 / MRD-1756 - validate the Contact Information Questionnaire for PO
> Adding E2E test to validate the Contact Information Questionnaire 

- .circleci/config.yml
- package-lock.json
- package.json
This will match the version in the Docker image
> MRD-1712 Bump npm version

- .circleci/config.yml
This includes Node 18 rather than 16
> MRD-1712 Upgrade e2e-local pipeline machine image

- .circleci/config.yml
the e2e_test_preprod and e2e_test_dev job runs the test that are in the new make-recall-decision-e2e-tests repo
> MRD-1788: Updated the pipeline to Run the E2E tests from the new e2e-test repo.

- integration_tests/integration/risk.spec.ts
- server/views/components/mappa-widget/template.njk
> mrd-1936_mappa-error-message: change to MAPPA error message text 😃

- server/monitoring/azureAppInsights.ts
This is a bit of an experiment to see if this provides us with page load timings in App Insights.
> MRD-2170 Enable web instrumentation

- server/controllers/recommendation/editReleasingPrisonController.test.ts
- server/controllers/recommendation/editReleasingPrisonController.ts
- server/routes/recommendations.ts
- server/textStrings/en.ts
- server/views/pages/recommendations/checkBookingDetails.njk
- server/views/pages/recommendations/editReleasingPrison.njk
Don't push this unless the associated api PR has been merged.
> MRD-2191 - edit releasing prison

- server/controllers/caseSummary/caseSummaryController.test.ts
- server/controllers/caseSummary/caseSummaryController.ts
- server/views/pages/caseSummary.njk
Picked in QA. Copy was incorrect
> amendment to text in  banners

- server/controllers/recommendation/checkBookingDetailsController.test.ts
- server/controllers/recommendation/checkBookingDetailsController.ts
- server/views/pages/recommendations/editGender.njk
- server/views/pages/recommendations/editMappaLevel.njk
Reverts ministryofjustice/make-recall-decision-ui#1049
> Revert "MRD-2245 - edit mappa level"

- package-lock.json
- package.json
This reverts commit cd23ccc4734d9ad1bc3043ddbee8c23cdc23d368.
> Revert "Update dependency applicationinsights to v3 (#1221)"

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Added probation into PreProd and Prod
> Allowlist Update

- .circleci/config.yml
- Dockerfile
- integration_tests/accessibility/accessibility.spec.ts
- integration_tests/integration/recommendation.spec.ts
- package-lock.json
- package.json
- server/controllers/recommendation/bookToPpudController.ts
- server/controllers/recommendation/booktoPpudController.test.ts
- server/controllers/recommendation/recordConsiderationRationaleController.test.ts
- server/controllers/recommendation/recordConsiderationRationaleController.ts
- server/controllers/recommendation/taskListConsiderRecallController.test.ts
- server/controllers/recommendation/taskListConsiderRecallController.ts
- server/routes/recommendations.ts
- server/textStrings/en.ts
- server/utils/constants.ts
- server/views/pages/recommendations/recordConsiderationRationale.njk
- server/views/pages/recommendations/responseToProbation.njk
- server/views/pages/recommendations/triggerLeadingToRecall.njk
including various package updates and : push to ND, dont create blank minute, missing back link, 
remove-logic-for-AC5-from-njk-pages-1273
> Reapplying various updates removed to allow Probation allowlist (Tmp patch)

- docs/tests.md
- server/controllers/recommendation/checkBookingDetailsController.test.ts
- server/controllers/recommendation/checkBookingDetailsController.ts
- server/services/userService.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
We are sometimes getting names (first, middle & last) from other systems (e.g. NOMIS) in all-caps. With these changes we adjust the names in such cases before presenting them to the user.
> MRD-2619 Correct PPCS names capitalisation

- server/@types/make-recall-decision-api/models/PpudCreateRecallRequest.ts
- server/booking/updateRecall.test.ts
- server/booking/updateRecall.ts
- server/controllers/recommendation/bookToPpudController.ts
- server/controllers/recommendation/bookingSummaryController.test.ts
- server/controllers/recommendation/bookingSummaryController.ts
- server/controllers/recommendation/booktoPpudController.test.ts
- server/controllers/recommendation/checkBookingDetailsController.test.ts
- server/controllers/recommendation/checkBookingDetailsController.ts
- server/controllers/recommendations/helpers/ppudMinutes.test.ts
- server/controllers/recommendations/helpers/ppudMinutes.ts
- server/controllers/recommendations/helpers/rosh.test.ts
- server/controllers/recommendations/helpers/rosh.ts
- server/views/pages/recommendations/bookingSummary.njk
- server/views/pages/recommendations/checkBookingDetails.njk
Always create a minute in PPUD. If there is additional text added during upload of Supporting Docs, append that text to the minute
> MRD-2610 Combining PPUD Minutes

- server/@types/make-recall-decision-api/models/PpudUpdateOffenceRequest.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/booking/updateOffence.test.ts
- server/booking/updateOffence.ts
- server/controllers/recommendation/matchIndexOffenceController.test.ts
- server/controllers/recommendation/matchIndexOffenceController.ts
- server/views/pages/recommendations/matchIndexOffence.njk
Allow optional text comment when entering ppud index offence
> MRD-2608 Adding optional text for ppud index offence

- package-lock.json
Update addresses
[CVE-2025-5889](https://github.com/advisories/GHSA-v6h2-p8h4-qcjw)
> Update brace-expansion version

- server/views/components/summary-list/template.njk
- server/views/pages/recommendations/ppcs/editCustodyGroup.njk
- server/views/pages/recommendations/ppcs/indeterminateSentence/selectIndeterminatePpudSentence.njk
Styling updated after discussion with design colleagues.
> MRD-2685 Update Indeterminate pages styling

- data/recommendations/recommendationGenerator.ts
- server/@types/make-recall-decision-api/models/RecommendationResponse.ts
- server/controllers/recommendation/recallTypeController.test.ts
- server/controllers/recommendation/recallTypeController.ts
- server/controllers/recommendations/recallType/availableRecallTypes.test.ts
- server/controllers/recommendations/recallType/availableRecallTypes.ts
- server/controllers/recommendations/recallType/inputDisplayValues.test.ts
- server/views/partials/layout.njk
- server/views/partials/recommendation/recallTypeFTR.njk
- server/views/partials/recommendation/recallTypeFTRConditionsPanel.njk
The recall-type page is updated to support the path where an FTR
is mandated due to the answers given to the suitability questions.
> MRD-2775 FTR48 mandated FTR path

- server/controllers/recommendation/recallTypeController.ts
- server/controllers/recommendation/suitabilityForFixedTermRecallController.test.ts
- server/controllers/recommendation/suitabilityForFixedTermRecallController.ts
- server/utils/fixedTermRecallUtils.test.ts
- server/utils/fixedTermRecallUtils.ts
[MRD-2854](https://dsdmoj.atlassian.net/browse/MRD-2854)
[MRD-2855](https://dsdmoj.atlassian.net/browse/MRD-2855)
Handle ftr details between mandatory and discretionary requirments changing
[MRD-2854]: https://dsdmoj.atlassian.net/browse/MRD-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MRD-2855]: https://dsdmoj.atlassian.net/browse/MRD-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MRD-2854/MRD-2855: Corretions to selected recall details

- integration_tests/integration/recommendationTaskList.spec.ts
- server/views/partials/taskList/circumstances.njk
- server/views/partials/taskList/recommendation.njk
> [MRD-2836]: Re-organising task list structure
