helm_deploy/make-recall-decision-ui/values.yaml

This is needed for the alerts templates - it's supplied in the env
specific configs, but for some reason we need a default.

Set a default value for `targetApplication`

---

.circleci/config.yml

This allows the E2E checks to be invoked and checked by the API
pipeline.

Allow the E2E (environment) checks to be ran as workflows

---

.circleci/config.yml
.gitignore
docker-compose.yml
package.json
scripts/run-e2e-tests-on-ci.sh
scripts/start-services-for-e2e-tests.sh
scripts/stop-services-for-e2e-tests.sh

The way this works is pulling down both UI and API, spinning up the `docker-compose` stack in both repos (connected on the same virtual network), then running the E2E's over those services.
The downside to this is that it takes ~3 minutes to build and spin up the stack, then however long the E2E's take... Not a lot we can do about that though I'm afraid. 😞

MRD-28: Run the E2E tests "locally" on CI

---

.circleci/config.yml

This executor uses the modern `cimg` redis images.

Update the node/redis executor

---

.circleci/config.yml
README.md
scripts/start-services-for-e2e-tests.sh
scripts/start-services-no-ui.sh
scripts/stop-services-for-e2e-tests.sh

This adds options to control when to...
- Run `docker-compose pull` (this isn't needed all the time)
- Build `hmpps-auth` (only on M1 macs)
The `hmpps-auth` build step is needed at least once if you're running an M1 mac as the currently distributed container isn't multi arch and has running problems on M1 silicon.

MRD-107: Make the start scripts work for M1 macs

---

api/responses/get-case-licence-history.json
server/controllers/caseSummary/caseSummary.test.ts
server/views/partials/caseLicenceHistory.njk

- use more realistic test mock for licence history contact summary array
- fix date sort by contact date - with the MoJ sortable table component you can specify a value to do the sort comparison on, using the [`data-sort-value` attribute](https://github.com/ministryofjustice/make-recall-decision-ui/pull/56/files#diff-898ab0ad102bfdbf488b3c12599bc9eeab9293135120597e1d15e087a66da515R30) - for dates, it should be the ISO-formatted date rather than the presentation-formatted date (eg 5th May 2022)

MRD-124 - Licence history - bigger test mock; fix date sort

---

.circleci/config.yml

This should ensure they get through the IP allow list on the ingress

Make the environment e2e use a restricted set of IPs

---

package-lock.json
package.json

This fixes the `check_outdated` failure from this morning.

Update the govuk-frontend package.

---

server/@types/dates.d.ts
server/controllers/caseSummary/utils/filterContactsByDateRange.test.ts
server/controllers/caseSummary/utils/filterContactsByDateRange.ts
server/middleware/parseUrl.test.ts
server/middleware/parseUrl.ts
server/utils/dates/convert.test.ts
server/utils/dates/convert.ts
server/utils/dates/index.ts
server/utils/errors.test.ts
server/utils/errors.ts
server/utils/utils.ts

These will be used by the next PR, to filter licence history contacts by date range.
Utils:
- filterContactsByDateRange
- parseUrl - make URL components available to views
- convertGmtDatePartsToUtc - convert the day/month/year that was entered into a date input, to a ISO string or error object
- formatValidationErrorMessage - render an error message using a validation error code

MRD-148 - Utility functions for date filters feature

---

assets/sass/local.scss
cypress_shared/commands.ts
cypress_shared/index.d.ts
integration_tests/integration/caseSummary.spec.ts
integration_tests/integration/licenceHistory.spec.ts
integration_tests/integration/personSearch.spec.ts
server/controllers/caseSummary/caseSummary.ts
server/controllers/caseSummary/utils/getCaseSection.ts
server/controllers/caseSummary/utils/groupContactsByStartDate.test.ts
server/controllers/caseSummary/utils/groupContactsByStartDate.ts
server/controllers/caseSummary/utils/transformLicenceHistory.test.ts
server/controllers/caseSummary/utils/transformLicenceHistory.ts
server/middleware/featureFlags.ts
server/routes/index.ts
server/utils/nunjucks.ts
server/utils/nunjucksSetup.ts
server/views/partials/caseLicenceHistory.njk
server/views/partials/layout.njk

- to enable the feature add `?dateFilters=1` to the URL
- filter contacts by date range
- split licence history transform functions to their own files

MRD-148 - Filter licence history contacts by date range (under a feature flag)

---

e2e_tests/integration/caseSummary.feature
e2e_tests/integration/stepDefinitions/index.ts
integration_tests/integration/caseSummary.spec.ts
server/views/partials/caseLicenceHistory.njk
server/views/partials/casePersonalDetails.njk

MRD-148 - Licence history - hierarchical headings for results list, for screen readers. Extend E2E test to cover date filter
MRD-117 - personal details - render address parts on separate lines

MRD-148 and MRD-117 - quick fixes

---

.circleci/config.yml

Temporary workaround for preprod env being unavailable due to data refresh

Allow deploys even with failing preprod e2e

---

integration_tests/integration/contactHistory.spec.ts
server/controllers/caseSummary/contactHistory/filterContactsBySearch.test.ts
server/controllers/caseSummary/contactHistory/filterContactsBySearch.ts
server/controllers/caseSummary/contactHistory/transformContactHistory.test.ts
server/views/partials/caseContactHistory.njk

The bug was: when multiple search terms were specified, for at least one of the contact fields (description, notes, outcome, enforcement action), **all** search terms had to match against that field
The new behaviour is: as long as each of the search terms has a match in at least one of the fields, then the contact is included in results.

MRD-205 - Fix bug where all terms had to match in the same contact field

---

server/middleware/setUpSentry.ts

This was causing every API error to cause a secondary error because Sentry was being passed a non-error instance

MRD-294 - Ignore 'non-error exceptions'

---

server/middleware/setAnalyticsId.ts

Data will be sent to both universal and GA4 accounts

MRD-546 - Restore universal GA IDs (dual connect)

---

integration_tests/integration/recommendation.spec.ts
server/views/pages/recommendations/recallType.njk
server/views/pages/recommendations/sensitiveInformation.njk

Depending on context:
- sensitive info links back to 3 different pages
- indeterminate / extended recall type links back to 2 different pages

MRD-607 - Back links

---

e2e_tests/integration/recallDeterminate.feature
server/controllers/recommendations/emergencyRecall/formValidator.test.ts
server/controllers/recommendations/emergencyRecall/formValidator.ts
server/controllers/recommendations/recallType/formValidator.test.ts
server/controllers/recommendations/recallType/formValidator.ts
server/controllers/recommendations/recallTypeIndeterminate/formValidator.test.ts
server/controllers/recommendations/recallTypeIndeterminate/formValidator.ts
server/views/pages/recommendations/emergencyRecall.njk

also - fix for when user clicks on 'what you recommend' from no recall task list, and on clicking continue is wrongly returned to the no recall task list

MRD-691 - Show emergency recall page after fixed term recall

---

scripts/start-services-for-e2e-tests-local.sh
scripts/start-services-for-e2e-tests.sh

Set profile to dev for e2e tests to ensure API builds with AWS SNS deactivated, this preserves pipeline by removing dependency on localstack.

mrd-285_domain-events

---

server/@types/contactTypes.ts
server/@types/index.d.ts
server/controllers/caseSummary/caseSummary.test.ts
server/controllers/caseSummary/contactHistory/filterContactsByContactType.ts
server/controllers/caseSummary/contactHistory/filterContactsByDateRange.ts
server/controllers/caseSummary/contactHistory/filterContactsBySearch.ts
server/controllers/caseSummary/contactHistory/helpers/contactTypes.test.ts
server/controllers/caseSummary/contactHistory/helpers/contactTypes.ts
server/controllers/caseSummary/contactHistory/helpers/decorateGroups.ts
server/controllers/caseSummary/contactHistory/transformContactHistory.ts
server/controllers/caseSummary/getCaseSection.ts
server/data/fetchFromCacheOrApi.ts
server/data/makeDecisionApiClient.ts
server/utils/nunjucks.ts
server/views/pages/recommendations/managerReview.njk

also, load system generated contacts in all cases (whether `flagShowSystemGenerated` is enabled or not) - managing the redis cache is needlessly complex if we store responses with both flag enabled and disabled.

MRD-1004 - Separate types for contacts to their own file

---

server/views/pages/recommendations/reviewPractitionersConcerns.njk

modified reviewPractionersConcern nunjucks template to allow linebreaks around freetext entries

mrd-1596_line-breaks-not-appearing-in-text-sent-from-pp-to-spo

---

renovate.json

Renovate repeatedly suggests upgrading to v5. We need to do that more intentionally so switching off until we have gone to v5.

Tell Renovate to ignore govuk-frontend

---

renovate.json

Temporarily switch off eslint upgrades until v9 is supported by typescript-eslint

Tell Renovate to ignore eslint

---

.circleci/config.yml

CircleCI 2004 Ubuntu images are about to reach end-of-life...bumped

bump circleci ubuntu image version

---

package-lock.json

Our project pulls in cross-spawn as an indirect dependency. The version we are pulling in has a known CVE vulnerability, so we're ugprading it to the latest known version without it.

Upgrade cross-spawn

---

api/responses/get-case-risk.json
docs/tests.md
integration_tests/integration/risk.spec.ts
server/controllers/caseSummary/caseSummaryController.ts
server/views/components/predictor-score/template.njk
server/views/components/predictor-timeline-section/template.njk
server/views/partials/caseRisk.njk

ARN switched to a different set of OSP values, OSP/DC and OSP/IIC.
With this change, the new values are displayed instead of the old
ones if present, with the relevant labels updated accordingly. If
neither new nor old values are present, the new labels are
displayed above the 'Data not available.' messages.
The timeline will also reflect the new and old values.

Mrd 2529 display new osp values

---

integration_tests/integration/risk.spec.ts
server/utils/nunjucks.ts
server/utils/nunjucksSetup.ts
server/views/components/predictor-indicator/template.njk
server/views/components/predictor-score/template.njk
server/views/partials/caseRisk.njk

The check on the level value was incorrect for OSP/C and OSP/DC values in the
case of a value of VERY_HIGH: the value itself is 'VERY_HIGH', with an
underscore, while the value checked against was 'VERY HIGH', with a space in
between. This was resulting in the label marker for VERY_HIGH cases to be
displayed in the middle of the rating bar, rather than on the right-most
section, due to the label not having the right class assigned to it. This is
corrected here.
It was also noticed that the wrong CSS class was assigned to the display label
for LOW OSP/C and OSP/DC scores: the one corresponding to the MEDIUM one
was used instead. This is corrected here.

MRD-2529 Fix OSP/C & OSP/DC label displays

---

server/controllers/recommendations/recallReceived/formValidator.test.ts

recallReceieved formValidator expected a hardcoded resultant year of 2024 despite the test's input values using the current year. Year also reduced by 1 since the validation expects the date to be in the past.

correcting a test's hardcoded reference to the year 2024

---

package-lock.json
package.json

Bump of cypress-multi-reports to a version whose mocha dependency no longer depends on nanoid
make-recall-decision-ui@0.0.1 /Users/rick.livesey/git/make-recall-decision-ui
└─┬ cypress-multi-reporters@1.6.4
└─┬ mocha@10.2.0
└── nanoid@3.3.3
-cypress-multi-reporters@1.6.4 depends on mocha@10.2.0
-mocha@10.2.0 is the last version with a nanoid dependency (this was the version we used), the next version (10.3.0) loses it
-cypress-multi-reporters@2.0.4 (the latest) depends on mocha 11.0.1
https://github.com/advisories/GHSA-mwcw-c2x4-8c55

bump of cypress-multi-reports to a ver whose mocha dependency no longer depends on nanoid CVE-2024-55565

---

package-lock.json
package.json

There isn't a version of cypress-multi-report that depends on a version of mocha which doesn't have a nanoid dependency, so this forces c-m-r to use the next version of mocha which drops that dependency.
More info on c-m-r / mocha reporters:
https://mochajs.org/#reporters

Bump cypress multi reporters nanoid vuln CVE 2024 55565 force mocha bump

---

integration_tests/integration/recommendation.spec.ts
server/views/pages/recommendations/editMappaLevel.njk

Given a PPCS user is Booking On a PoP using CaR
When they visit the ‘Edit MAPPA’ page and the MAPPA does not have a value
Then display the following:
From the Part A
MAPPA level: Unknown

mrd 2612 display graceful message when mappa value unknown

---

integration_tests/integration/recommendation.spec.ts
server/@types/make-recall-decision-api/models/PpudUpdateSentenceRequest.ts
server/@types/make-recall-decision-api/models/RecommendationResponse.ts
server/booking/createOrUpdateSentence.test.ts
server/booking/createOrUpdateSentence.ts
server/booking/updateRelease.test.ts
server/controllers/recommendation/editLegislationReleasedUnderController.test.ts
server/controllers/recommendation/editLegislationReleasedUnderController.ts

The existing 'Released Under' field for PPUD Offender Releases is now re-used
also for PPUD Offender Sentences' 'Sentenced Under' field. This is reflected
both in its storage as a separate, new legislationSentencedUnder field in the
bookRecallToPpud structure as well as in the requests for creating and updating
PPUD sentences, as the legislation under which an offender was sentenced should
be the same as the one under which they were released.

MRD-2609 Set 'Sentenced Under' field in PPUD Sentence

---

scripts/start-services-for-e2e-tests-local.sh
scripts/start-services-for-e2e-tests.sh

Reverting management endpoints (health/info/prometheus) back to standard HTTP ports.
These were overridden to use 8081 on 03/05/22 by Darren Oakley for MRD-11

MRD-2526 Fixing info endpoint (move to standard port)

---

server/views/pages/recommendations/editReleasingPrison.njk
server/views/pages/recommendations/matchIndexOffence.njk

The placeholder text in the two autocomplete fields has been changed from
"Select X" to "Search for X", as the latter has a stronger implication or
suggestion of the field allowing the user to input text to search for the
option they want to select, rather than just having to scroll down to find the
appropriate option. The words "Type" and "Write" were also considered, but
discarded due to not being applicable in all cases (e.g. when certain
accessibility input devices are being used by the user).

MRD-2611 Update autocomplete placeholder text

---

server/controllers/startPage/startPage.test.ts
server/controllers/startPage/startPage.ts
server/data/fetchFromCacheOrApi.test.ts
server/data/fetchFromCacheOrApi.ts

Adding caching of PPUD user api response for 1 week
Including additional override parameter for items that should remain cached for longer than the default (1d)

mrd-2653 Cache PPUD user hits

---

server/controllers/recommendation/custodyStatusController.test.ts
server/controllers/recommendations/custodyStatus/formValidator.test.ts
server/controllers/recommendations/custodyStatus/formValidator.ts

The Police Contact Details are reset/nulled if the Custody Status is changed from “Yes, police custody” to either of the other two options.
Original Aug '22 logic: MRD-559: DEV: If PoP in custody, don't show arrest issues / police contact pages
Updated Feb '24 logic: MRD-2391: [Approved] Stop selecting 'in custody' hiding police contact info from task list
According to the second card, the contact details should not be reset/nulled.

MRD-2682 police contact details reset if

---

.circleci/config.yml
.gitignore
scripts/start-services-for-e2e-tests-local.sh
server/views/components/summary-list/macro.njk
server/views/components/summary-list/template.njk
server/views/pages/recommendations/bookedToPpud.njk
server/views/pages/recommendations/checkBookingDetails.njk
server/views/pages/recommendations/searchPpudResults.njk

Changes to support MRD-2557, e2e local journey tests.
- Add new cypress env values to e2e_local_tests CircleCI job
- Update start-services-for-e2e-tests-local script to include new spring profile being added to the api to seed test data
- Required access to various Edit links on the checkBookingDetails page.
- The original version has little lacking in identifying information and had a number of inconsistencies with a well formed definition list (a.k.a a [Summary List](https://design-system.service.gov.uk/components/summary-list/) as defined by the GovUK Design system).
- To support this I have founded a summary list component that incorporates both the best practices for the definition list and ids key elements for retrieval during tests.
- This has then replaced the inline summary list …

[MRD-2557]: PPCS e2e local journey

---

.circleci/config.yml

The pre-prod e2e test run needs to be removed, as the data
originates in prod and shouldn't be used for anything other
than its original purpose (GDPR).
Additionally, MFA has just been added to pre-prod, which
would prevent the automated tests from going through anyway.

MRD-2744 Remove pre-prod e2e tests

---

package-lock.json
package.json

The following dependencies have been updated to address vulnerabilities:
- babel to ^7.26.10 - the version has been overridden, as the consumer of it,
ts-jest, doesn’t pull in a high enough version even in its latest release.
No breaking changes are listed in the babel change for our update range.
- mocha to ^10.6.0 - also overridden due to the consumers
(cypress-multi-reporters and mocha-unit-reporter) not up-to-date even on
their latest versions. No breaking changes are listed for our update range.
- super agent to ^10.0.0 - this was to bring up the version of formidable,
one of its dependencies which had a vulnerability. No breaking changes have
been listed since super agent released 6.1.
Note also that the ts-jest dependency version expression has been changed from
^29.1.2 to ~29.1.2. …

MRD-2743 Update dependencies

---

server/controllers/personSearch/personSearchResults.test.ts
server/controllers/personSearch/personSearchResults.ts
server/controllers/personSearch/personSearchResultsByName.test.ts
server/controllers/personSearch/personSearchResultsByName.ts
server/views/pages/paginatedPersonSearchResults.njk

To reflect the changes in https://github.com/ministryofjustice/make-recall-decision-api/pull/1179
As the split in search endpoints has lead to different assumptions as the the index of the first page (by crn: 1, by name: 0) the managing of this has been moved into the API as an implementation details and now the UI and API will always communicate on the understanding that the first page has index 1.

Update fix: paging for search results - by crn vs name

---

data/recommendations/recallTypeGenerator.ts
data/recommendations/recommendationGenerator.ts
data/utils.ts
integration_tests/integration/recommendationFormValidation.spec.ts
integration_tests/integration/recommendations/partA/recallType.spec.ts
server/controllers/recommendation/recallTypeController.test.ts
server/controllers/recommendation/recallTypeController.ts
server/controllers/recommendations/recallType/formValidator.test.ts
server/helpers/ppudSentence/ppudSentenceHelper.test.ts
server/testUtils/booleanUtils.ts
server/textStrings/en.ts
server/views/partials/recommendation/recallTypeFTR.njk
server/views/partials/recommendation/recallTypeFTRDiscretionaryConditionsPanel.njk

[MRD-2786 Change recommendation screen - suitability for FTR [Discretionary path] or Standard](https://dsdmoj.atlassian.net/browse/MRD-2786)
Add discretionary panel to the recall type controller if the FTR48 feature is enabled and any of the exclusion criteria (values from the suitability for recall type page) apply.
Else continue to display the mandatory panel.

Add non mandatory (discretionary) panel to recall type for FTR48

---

integration_tests/integration/recommendationFormValidation.spec.ts
integration_tests/integration/recommendations/partA/recallType.spec.ts
server/controllers/recommendations/recallType/formOptions.ts
server/controllers/recommendations/recallType/formValidator.test.ts
server/controllers/recommendations/recallType/formValidator.ts
server/textStrings/en.ts
server/utils/lists.test.ts
server/views/pages/recommendations/recallType.njk

Modulate noRecallType error messages into Mandatory and Discretionary variants
Discretionary recall error message referring to all three options: Standard, Fixed Term and no recall
Update Mandatory recall error message referring only to Fixed Term and No Recall
Additionally, change the order of `Fixed Term` and `Standard` Recall options as UCD wishes Fixed Term to be the presumed default and offered as the lead option.
This matches the designs in [MRD-2775](https://dsdmoj.atlassian.net/browse/MRD-2775) but it was not apparent that the order of the inputs mattered until we noticed that the error message listed them in a different order so they were simply in the order they have always been.
[MRD-2775]: https://dsdmoj.atlassian.net/browse/MRD-2775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

FTR48 Fixups: Recall Type error message

---

server/views/partials/taskList/circumstances.njk

The suitability page is relevant for all non-extended, non-indeterminate
sentences. The display criteria for the link to the page in the task list is
amended here.

MRD-2833 Show suitability for STD in task list

---

helm_deploy/values-dev.yaml

Rather than route traffic to make recall decision API endpoints, this PR takes advantage of the fact that both the API and UI are in the same namespace which allows us to route traffic directly to services in that namespace without the overhead of routing out and back into the ingress - which is the cause of all the 499 errors we see.

changes mrd api ingress to use local service routing
